---

- name: Install ElasticSearch
  hosts: Elasticsearch
  roles: 
  - elasticsearch

- name: Install Kibana
  hosts: Kibana
  roles: 
  - kibana

- name: Install Logstash
  hosts: Logstash
  roles: 
  - logstash

- name: Install FileBeat Agent
  hosts: web_servers
  roles: 
  - filebeat
  
  